
import  { NewEnvGroup } from "./EnvGroup"
import { nanoid } from "nanoid";

export const initGroups:NewEnvGroup[] = [{
    id:nanoid(),
    createdAt: Date.now(),
    name: "nodejs",
    getListScript:`Ci8qKgogKiDojrflj5bnjq/looPku5PlupPliJfooajmlbDmja4KICogQHBhcmFtIHsgQ29uZmlnVHlwZSB9IGNvbmZpZyDnjq/looPphY3nva4KICogQHBhcmFtIHsgVXRpbHNUeXBlIH0gdXRpbHMg5bel5YW35Ye95pWw6ZuG5ZCICiAqIEBwYXJhbSB7IFJlc3VsdFR5cGVbXSB9IOWIl+ihqOaVsOaNrgogKi8KYXN5bmMgKGNvbmZpZyx1dGlscyk9PnsKICAgIGNvbnN0IGxpc3QgPSBhd2FpdCB1dGlscy5mZXRjaChjb25maWcucm91dGVVcmwpLnRoZW4ocmVzPT5yZXMuanNvbigpKQogICAgY29uc3QgdmVyVGV4dHMgPSAiMTgsMjIsMjQsMjUiLnNwbGl0KCcsJykubWFwKGE9Pid2JythKQogICAgbGV0IHZlcnNpb25zID0gbGlzdC5maWx0ZXIoYT0+YS50eXBlPT0nZGlyJyAmJiBhLmNhdGVnb3J5PT0nbm9kZScgJiYgdmVyVGV4dHMuaW5jbHVkZXMoYS5uYW1lLnNwbGl0KCcuJylbMF0pKQogICAgLy/np7vpmaR2LC8KICAgIHZlcnNpb25zLmZvckVhY2goaXRlbT0+aXRlbS5uYW1lPWl0ZW0ubmFtZS5yZXBsYWNlKC9bdi9dL2csICcnKSkKICAgIC8v54mI5pys5o6S5bqPCiAgICBjb25zdCB2ZXJMaXN0ID0gdmVyc2lvbnMubWFwKGE9PmEubmFtZSkuc29ydCh1dGlscy52ZXJzaW9uQ29tcGFyZSkucmV2ZXJzZSgpCgogICAgbGV0IHJlc3VsdCA9IFtdCiAgICB2ZXJMaXN0LmZvckVhY2goKHZlcixpbmRleCk9PnsKICAgICAgICBsZXQgdmVySXRlbSA9IHZlcnNpb25zLmZpbmQoYT0+YS5uYW1lPT12ZXIpCiAgICAgICAgbGV0IG5hbWUgPSB2ZXJJdGVtLm5hbWUKICAgICAgICBsZXQgdXJsID0gdmVySXRlbS51cmwKICAgICAgICByZXN1bHQucHVzaCh7IHZlcnNpb246bmFtZSwgc29ydDppbmRleCAsdXJsOmAke3VybH1ub2RlLXYke25hbWV9LXdpbi14NjQuemlwYCB9KQogICAgfSkKICAgIHJldHVybiByZXN1bHQKfQo=`,
sort: 1,
routeUrl:'https://registry.npmmirror.com/-/binary/node/'
},{
    id:nanoid(),
    createdAt: Date.now(),
    name: "java",
    getListScript:`Ci8qKgogKiDojrflj5bnjq/looPku5PlupPliJfooajmlbDmja4KICogQHBhcmFtIHsgQ29uZmlnVHlwZSB9IGNvbmZpZyDnjq/looPphY3nva4KICogQHBhcmFtIHsgVXRpbHNUeXBlIH0gdXRpbHMg5bel5YW35Ye95pWw6ZuG5ZCICiAqIEBwYXJhbSB7IFJlc3VsdFR5cGVbXSB9IOWIl+ihqOaVsOaNrgogKi8KYXN5bmMgKGNvbmZpZyx1dGlscyk9PnsKCiAgICBmdW5jdGlvbiBwYXJzZURpcmVjdG9yeUxpc3RpbmcoaHRtbFN0cmluZykgewogICAgICAgIGNvbnN0IHJlc3VsdHMgPSBbXTsKICAgICAgICAvLyDmraPliJnooajovr7lvI/ljLnphY0gaHJlZiDlkozml7bpl7QKICAgICAgICBjb25zdCByZWdleCA9IC88YSBocmVmPSIoW14iXSspIltePl0qPi4qPzxcL2E+XHMrKFxkezJ9LVtBLVpdW2Etel17Mn0tXGR7NH0gXGR7Mn06XGR7Mn0pL2c7CiAgICAgICAgCiAgICAgICAgbGV0IG1hdGNoOwogICAgICAgIHdoaWxlICgobWF0Y2ggPSByZWdleC5leGVjKGh0bWxTdHJpbmcpKSAhPT0gbnVsbCkgewogICAgICAgICAgICByZXN1bHRzLnB1c2goewogICAgICAgICAgICAgICAgbmFtZTogbWF0Y2hbMV0ucmVwbGFjZSgvXC8kLywgJycpLAogICAgICAgICAgICAgICAgdGltZTogbWF0Y2hbMl0KICAgICAgICAgICAgfSk7CiAgICAgICAgfQogICAgICAgIAogICAgICAgIHJldHVybiByZXN1bHRzOwogICAgfQoKICAgIGNvbnN0IGh0bWxUZXh0ID0gYXdhaXQgdXRpbHMuZmV0Y2goY29uZmlnLnJvdXRlVXJsKS50aGVuKHJlcz0+cmVzLnRleHQoKSkKICAgIGNvbnN0IGxpc3QgPSBwYXJzZURpcmVjdG9yeUxpc3RpbmcoaHRtbFRleHQpCiAgICBjb25zdCB2ZXJUZXh0cyA9ICIxMSwxNiwxOCwyMSwyNCIuc3BsaXQoJywnKQogICAgbGV0IHZlcnNpb25zID0gbGlzdC5maWx0ZXIoYT0+dmVyVGV4dHMuaW5jbHVkZXMoYS5uYW1lLnNwbGl0KCcuJylbMF0pKQogICAgLy/niYjmnKzmjpLluo8KICAgIGNvbnN0IHZlckxpc3QgPSB2ZXJzaW9ucy5tYXAoYT0+YS5uYW1lKS5zb3J0KHV0aWxzLnZlcnNpb25Db21wYXJlKS5yZXZlcnNlKCkKCiAgICBsZXQgcmVzdWx0ID0gW10KICAgIHZlckxpc3QuZm9yRWFjaCgodmVyLGluZGV4KT0+ewogICAgICAgIGxldCB2ZXJJdGVtID0gdmVyc2lvbnMuZmluZChhPT5hLm5hbWU9PXZlcikKICAgICAgICBsZXQgbmFtZSA9IHZlckl0ZW0ubmFtZQogICAgICAgIGxldCB1cmwgPSBgJHtjb25maWcucm91dGVVcmx9LyR7dmVySXRlbS5uYW1lfS9vcGVuamRrLSR7dmVySXRlbS5uYW1lfV93aW5kb3dzLXg2NF9iaW4uemlwYAogICAgICAgIHJlc3VsdC5wdXNoKHsgdmVyc2lvbjpuYW1lLCBzb3J0OmluZGV4ICx1cmwgfSkKICAgIH0pCiAgICByZXR1cm4gcmVzdWx0Cn0K`,
sort: 2,
routeUrl:'https://mirrors.huaweicloud.com/openjdk/'
}]
