/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnvSidebar: typeof import('./src/components/EnvSidebar.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TsEditorDialog: typeof import('./src/components/TsEditorDialog.vue')['default']
    VersionList: typeof import('./src/components/VersionList.vue')['default']
  }
}
